<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework> <!-- THIS MUST BE 9.0 -->
    <AssemblyVersion>1.0.4.0</AssemblyVersion>
    <FileVersion>1.0.4.0</FileVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Authors>reallydumbdog</Authors>
    <Company>reallydumbdog</Company>
    <Description>An announcement plugin designed for ElegantFin skin.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.0" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
  </ItemGroup>
</Project>